#!/bin/sh
cd $(git rev-parse --show-toplevel)
cd mini_template
cargo test || { echo 'mini_template failed' ; exit 1; }
cd ../mini_template_macro
cargo test || { echo 'mini_template_macro failed' ; exit 1; }
exit 0
